language: erlang
script: "make clean deps compile xref test"
otp_release:
  # DISABLED 18.1. Travis is failing by no reason
  # - 18.1
  - 17.5
  # DISABLED: https://github.com/leveldb-erlang/h2leveldb/issues/1#issuecomment-102654760
  # - R16B03-1
